version: "3.8"
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: ${DB_NAME}
    restart: always
volumes:
  db-volume:
